#    dubbo 配置
dubbo:
  application:
    name: huayun-web
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 50000
  scan:
    base-packages: cn.ddnd.huayun.huayun.service
  consumer:
    timeout: 50000

spring:
  redis:
    host: 127.0.0.1
  mail:
    host: smtp.163.com
    username: dodoname@163.com
    password: 123123qwe #gzhogknhbmfebgbi #123123qwe
    protocol: smtp
    properties: {"mail.smtp.auth":"true", "mail.smtp.ssl.enable":"true", "mail.smtp.socketFactory.class":"javax.net.ssl.SSLSocketFactory"}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/huayun?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    # Druid 配置
    initial-size: 8 #初始化连接大小
    min-idle: 5 #最小空闲连接数
    max-active: 10 #最大连接数
    query-timeout: 6000 #查询超时时间
    transaction-query-timeout: 6000 #事务查询超时时间
    remove-abandoned-timeout: 1800 #关闭空闲连接超时时间
    filters: stat,config
#    rabbitMQ 配置
  rabbitmq:
    virtual-host: /
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
  elasticsearch:
    jest:
      read-timeout: 9s


global:
  huayun:
    access-key-id: 36c34ff3094b4dec9786dcc35d1f0d41
    access-key-secret: b87e24ad3b00420fadec14a9260ca94e
    request-api-url: https://api.chinac.com/
    region: cn-suzhou1, cn-huaian, cn-beijing1, cn-guangzhou1, cn-chengdu, cn-anxi, cn-sz-meisheng
  rabbitmq:
    exchange: huayun.direct
    routing-key:
  monitor:
    title: 云主机告急提示 【华云】
    email: dodoname@163.com
  msm:
    app-code: 0a3e3bbf4b5f4f7599063eabb424ab76


server:
  port: 80
