spring:
#  rabbitmq 配置信息
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  elasticsearch:
    jest:
#      password: 760oA4j7BDLDDU2dUcer
#      username: elastic

global:
  rabbitmq:
    exchange: huayun.fanout
    routing-key:

  huayun:
    access-key-id: 36c34ff3094b4dec9786dcc35d1f0d41
    access-key-secret: b87e24ad3b00420fadec14a9260ca94e
    request-api-url: https://api.chinac.com/
    cloud-id: i-zz6rj39kty724
    router-id: r-sm7yj59iy6117, r-747yj59j9a2l
    lb-id:

  cloud:
    cpu: 100
    memory: 101
    disk-used: 102
    io-read: 103
    io-write: 104
    iops-read: 105
    iops-write: 106
    fip-in: 107
    fip-out: 108
